### ISSUE TITLE
Could we also use the web GUI for `WorkChain`s?

### ISSUE THREAD

**Issue by GeigerJ2** [aiidateam/aiida-workgraph#141]
I really like the web GUI of `WorkGraph` (if I manage to build it correctly in my dev version :D). I'm just wondering... how does it retrieve the data from AiiDA, e.g. the `process_state` for showing the "Real-time state"? Is it using the AiiDA REST API to fetch data from the database? Or running queries (seems unlikely)?

In any case, I've been wondering if it would be possible to also visualize the data for `WorkChain`s in a similar manner? Of course, a visualization of the full workflow wouldn't immediately be accessible for a `WorkChain`, but it could still be interesting to see finished and running processes. My hope is that this could be achieved with minimal coding effort, assuming that data is fetched from the database in a general-enough way, which I assume could be the case, as subprocesses of a `WorkGraph` should be similar enough to subprocesses of a `WorkChain` (or might even be `WorkChain`s themselves). I also like the idea of being able to pause and play processes and increase/decrease deamon workers from the web GUI interface (and these are not `WorkGraph` specific).

**Comment by superstar54** [comment]
>  how does it retrieve the data from AiiDA, e.g. the process_state for showing the "Real-time state"?

For AiiDA process, one can use AiiDA REST API directly to get the process info.

WorkGraph's case is more complex because the WorkGraph does not require the task to be an AiiDA process. Any python function can be a task, and the state of this non-AiiDA process task is store in the extras of the `WorkGraph` process.

> visualize the data for WorkChains in a similar manner?

We can. We are currently developing a node graph visualizer for AiiDA (the Google summer school project), which can be used for this purpose. 


> process and daemon control

Indeed, we can provide a GUI which allows users to:
- visualize node graph
- control process, pause/play/kill/delete
- control daemon
- setup/modify profile
- search jobs/data
- setup code/computer
...

In the long-term view, the GUI of WorkGraph should be a part of the AiiDA GUI.

**Comment by GeigerJ2** [comment]
> WorkGraph's case is more complex because the WorkGraph does not require the task to be an AiiDA process. Any python function can be a task, and the state of this non-AiiDA process task is store in the extras of the `WorkGraph` process.

Ah, I see, good point. Then it might already contain the functionality for `aiida-core` processes, as it even extends on that.

> We can. We are currently developing a node graph visualizer for AiiDA (the Google summer school project), which can be used for this purpose.

I'm aware of that, but I considered it to be a different project. As mentioned, my idea was that it might already be possible with the current `WorkGraph` web GUI, with minimal coding effort. I see, excited what comes out of the GSOC project then!

> Indeed, we can provide a GUI which allows users to:
> 
> * visualize node graph
> * control process, pause/play/kill/delete
> * control daemon
> * setup/modify profile
> * search jobs/data
> * setup code/computer
>   ...

AiiDA to the 🌔 🚀 

> In the long-term view, the GUI of WorkGraph should be a part of the AiiDA GUI.

OK, I see. Thanks for the insights!
