### ISSUE TITLE
Changing the name of `.value` for `SocketAny` to obtain AiiDA `Node`

### ISSUE THREAD

**Issue by GeigerJ2** [aiidateam/aiida-workgraph#293]
As noted with @mbercx in a recent meeting, using `SocketAny.value` to obtain the AiiDA `Node` can lead to a bit of a weird syntax, e.g. `.value.value` to get the value of an associated `Float` `Node`. We were thinking of using `.node`, but I realize that this returns the `DecoratedNode`. So do you think it makes sense to provide, e.g., a convenience method `.get_node()` to return the actual AiiDA `Node` that is contained in the `value` of the `SocketAny`? Or any other suggestions?

**Comment by superstar54** [comment]
H @GeigerJ2 , thanks for opening this issue. I agree that `task1.outputs["sum"].value.value` is redundant and unusual.

`.get_node` may conflict with the `.node` attribute. The task1.outputs["sum"].node gives the parent node (task) this socket attached to, thus gives `task1`. If we set `get_node` to return the value of the socket, there is a bit confuse.

Another solution is to add `raw_value` to the socket, so one can access the float by `task1.outputs["sum"].raw_value`.
```
@property
def raw_value(self):
    if hasattr(self.value, "value"):
        return self.value.value
    else:
        raise ...
```

**Comment by GeigerJ2** [comment]
Yeah, I thought using the `node` nomenclature can clash in various places ^^ I'm fine with the proposed `property` implementation to provide a shortcut for `value.value`. How about the name `node_value`, though? I think this clarifies nicely from where the `value` comes from, that is, an AiiDA `Node` (given that it doesn't clash with something else, again :D)

**Comment by superstar54** [comment]
`node_value` is good to me. Do you want to implement this?

**Comment by GeigerJ2** [comment]
With pleasure! I'd add the `property` code to `NodeSocket` in the `node-graph` repo, though. That seems to be the general entry point? I saw that there's `SocketAny` both in `node-graph`, as well as `aiida-workgraph`, but both of them eventually inherit from `NodeSocket`. Any objection?

**Comment by superstar54** [comment]
Thanks!
I recommend adding this to the `aiida-workgraph`. The `node-graph` is a low-level package and should remain decoupled from AiiDA. Since this functionality is required in all `Sockets` within the `WorkGraph`, it would be more appropriate to include it in `aiida_workgraph.socket.TaskSocket` directly. You can add the `node_value` property and leave the `get_node_value()` not implemented. Then you implement `get_node_value` in the `SocketAny` and return `.value.value`. In the feature, if we add `SocketDict`, it should return `.value.get_dict()`.
